services:

  kafka-init:
    image: confluentinc/cp-kafka:7.4.0
    container_name: kafka-init
    entrypoint: 
      - /bin/bash
      - -c
      - |
        set -e
        echo "STARTING INIT SCRIPT..."
        
        echo "Waiting for final synchronization..."
        sleep 5

        echo "Creating topics..."
        kafka-topics --bootstrap-server broker-kafka-1:9092,broker-kafka-2:9092,broker-kafka-3:9092 --create --if-not-exists --topic to-alert-system --replication-factor 2 --partitions 3
        kafka-topics --bootstrap-server broker-kafka-1:9092,broker-kafka-2:9092,broker-kafka-3:9092 --create --if-not-exists --topic to-notify --replication-factor 2 --partitions 3
        
        echo "VERIFICATION: List topics"
        kafka-topics --bootstrap-server broker-kafka-1:9092,broker-kafka-2:9092,broker-kafka-3:9092 --list
        
        echo "INIT SCRIPT COMPLETED."
    networks:
      - kafka-network
    depends_on:
      broker-kafka-1:
        condition: service_healthy
      broker-kafka-2:
        condition: service_healthy
      broker-kafka-3:
        condition: service_healthy

  broker-kafka-1:
    image: confluentinc/cp-kafka:7.4.0
    container_name: broker-kafka-1
    healthcheck:
      test: ["CMD-SHELL", "cub kafka-ready -b localhost:9092 1 20"]
      interval: 10s
      timeout: 10s
      retries: 5
      start_period: 60s
    environment:
      # --- Configurazione KRaft ---
      KAFKA_NODE_ID: 1
      KAFKA_PROCESS_ROLES: 'broker,controller'
      KAFKA_CONTROLLER_QUORUM_VOTERS: '1@broker-kafka-1:9093,2@broker-kafka-2:9093,3@broker-kafka-3:9093'
      # --- Listeners ---
      KAFKA_LISTENERS: 'PLAINTEXT://:9092,CONTROLLER://:9093'
      KAFKA_ADVERTISED_LISTENERS: 'PLAINTEXT://broker-kafka-1:9092'
      KAFKA_CONTROLLER_LISTENER_NAMES: 'CONTROLLER'
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: 'CONTROLLER:PLAINTEXT,PLAINTEXT:PLAINTEXT'
      # --- Altre Configurazioni ---
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 2
      KAFKA_TRANSACTION_STATE_LOG_REPLICATION_FACTOR: 2
      KAFKA_TRANSACTION_STATE_LOG_MIN_ISR: 2
      KAFKA_GROUP_INITIAL_REBALANCE_DELAY_MS: 0
      KAFKA_AUTO_CREATE_TOPICS_ENABLE: 'true'
      KAFKA_HEAP_OPTS: "-Xmx400M -Xms400M"
      CLUSTER_ID: 'MkU3OEVBNTcwNTJENDM2Qk'
      KAFKA_LOG_DIRS: /var/lib/kafka/data
    volumes:
      - kafka_data_1:/var/lib/kafka/data
    networks:
      - kafka-network

  broker-kafka-2:
    image: confluentinc/cp-kafka:7.4.0
    container_name: broker-kafka-2
    healthcheck:
      test: ["CMD-SHELL", "cub kafka-ready -b localhost:9092 1 20"]
      interval: 10s
      timeout: 10s
      retries: 5
      start_period: 60s
    environment:
      KAFKA_NODE_ID: 2
      KAFKA_PROCESS_ROLES: 'broker,controller'
      KAFKA_CONTROLLER_QUORUM_VOTERS: '1@broker-kafka-1:9093,2@broker-kafka-2:9093,3@broker-kafka-3:9093'
      KAFKA_LISTENERS: 'PLAINTEXT://:9092,CONTROLLER://:9093'
      KAFKA_ADVERTISED_LISTENERS: 'PLAINTEXT://broker-kafka-2:9092'
      KAFKA_CONTROLLER_LISTENER_NAMES: 'CONTROLLER'
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: 'CONTROLLER:PLAINTEXT,PLAINTEXT:PLAINTEXT'
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 2
      KAFKA_TRANSACTION_STATE_LOG_REPLICATION_FACTOR: 2
      KAFKA_TRANSACTION_STATE_LOG_MIN_ISR: 2
      KAFKA_GROUP_INITIAL_REBALANCE_DELAY_MS: 0
      KAFKA_AUTO_CREATE_TOPICS_ENABLE: 'true'
      KAFKA_HEAP_OPTS: "-Xmx400M -Xms400M"
      CLUSTER_ID: 'MkU3OEVBNTcwNTJENDM2Qk'
      KAFKA_LOG_DIRS: /var/lib/kafka/data
    volumes:
      - kafka_data_2:/var/lib/kafka/data
    networks:
      - kafka-network

  broker-kafka-3:
    image: confluentinc/cp-kafka:7.4.0
    container_name: broker-kafka-3
    healthcheck:
      test: ["CMD-SHELL", "cub kafka-ready -b localhost:9092 1 20"]
      interval: 10s
      timeout: 10s
      retries: 5
      start_period: 60s
    environment:
      KAFKA_NODE_ID: 3
      KAFKA_PROCESS_ROLES: 'broker,controller'
      KAFKA_CONTROLLER_QUORUM_VOTERS: '1@broker-kafka-1:9093,2@broker-kafka-2:9093,3@broker-kafka-3:9093'
      KAFKA_LISTENERS: 'PLAINTEXT://:9092,CONTROLLER://:9093'
      KAFKA_ADVERTISED_LISTENERS: 'PLAINTEXT://broker-kafka-3:9092'
      KAFKA_CONTROLLER_LISTENER_NAMES: 'CONTROLLER'
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: 'CONTROLLER:PLAINTEXT,PLAINTEXT:PLAINTEXT'
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 2
      KAFKA_TRANSACTION_STATE_LOG_REPLICATION_FACTOR: 2
      KAFKA_TRANSACTION_STATE_LOG_MIN_ISR: 2
      KAFKA_GROUP_INITIAL_REBALANCE_DELAY_MS: 0
      KAFKA_AUTO_CREATE_TOPICS_ENABLE: 'true'
      KAFKA_HEAP_OPTS: "-Xmx400M -Xms400M"
      CLUSTER_ID: 'MkU3OEVBNTcwNTJENDM2Qk'
      KAFKA_LOG_DIRS: /var/lib/kafka/data
    volumes:
      - kafka_data_3:/var/lib/kafka/data
    networks:
      - kafka-network
    
  kafka-ui: 
    image: provectuslabs/kafka-ui:latest
    container_name: kafka-ui
    depends_on:
      - broker-kafka-1
      - broker-kafka-2
      - broker-kafka-3
    ports:
      - "8080:8080"
    environment:
      KAFKA_CLUSTERS_0_NAME: local
      KAFKA_CLUSTERS_0_BOOTSTRAPSERVERS: broker-kafka-1:9092,broker-kafka-2:9092,broker-kafka-3:9092
      KAFKA_LOG_DIRS: /var/lib/kafka/data
    networks:
      - kafka-network
      
  alert-system:
    build: ./alert_system
    container_name: alert-system
    networks:
      - kafka-network
    restart: always
    depends_on:
      broker-kafka-1: 
        condition: service_healthy
      broker-kafka-2: 
        condition: service_healthy
      broker-kafka-3: 
        condition: service_healthy
      kafka-init:
        condition: service_completed_successfully

  alert-notifier-system:
    build: ./alert_notifier_system
    container_name: alert-notifier-system
    environment:
      - SMTP_SERVER=${SMTP_SERVER}
      - SMTP_PORT=${SMTP_PORT}
      - SENDER_EMAIL=${SENDER_EMAIL}
      - EMAIL_PASSWORD=${EMAIL_PASSWORD}
    networks:
      - kafka-network
    restart: always
    depends_on:
      broker-kafka-1:
        condition: service_healthy
      broker-kafka-2:
        condition: service_healthy
      broker-kafka-3:
        condition: service_healthy
      kafka-init:
        condition: service_completed_successfully

  api_gateway:
    build: ./api_gateway
    container_name: api_gateway
    ports:
      - "80:80"
      - "443:443"
    volumes:
      # Configurazione NGINX principale
      - ./api_gateway/nginx.conf:/usr/local/openresty/nginx/conf/nginx.conf:ro
      # Config Load Balancer
      - ./api_gateway/load_balancer.conf:/etc/nginx/conf.d/load_balancer.conf:ro
      # Certificati SSL
      - ./api_gateway/SSL:/etc/nginx/ssl:ro
      # Public Key per JWT
      - ./api_gateway/public_key.pem:/etc/nginx/keys/public.pem:ro
      # Script Lua per validare i token
      - ./api_gateway/jwt_validator.lua:/etc/nginx/lua/jwt_validator.lua:ro
    depends_on:
      user-manager:
        condition: service_started
      data-collector:
        condition: service_healthy
    restart: always
    networks:
      - gateway-network

  flights_db:
    image: mariadb:10.11
    container_name: flights_db
    environment:
      - MARIADB_DATABASE=${FLIGHTSDB_DATABASE}
      - MARIADB_USER=${FLIGHTSDB_USER}
      - MARIADB_PASSWORD=${FLIGHTSDB_PASSWORD}
      - MARIADB_ROOT_PASSWORD=${FLIGHTSDB_ROOT_PASSWORD}
    healthcheck:
      test: ["CMD", "healthcheck.sh", "--connect", "--innodb_initialized"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 30s
    networks:
      - data-network
    restart: on-failure
    volumes:
      - flightdb_data:/var/lib/mysql

  data-collector:
    build: ./data_collector
    container_name: data-collector
    environment:
      - SSL_CERT_FILE=${SSL_CERT_FILE}
      - PYTHONUNBUFFERED=1
      - DATA_COLLECTOR_PORT=${DATA_COLLECTOR_PORT}
      - FLIGHTSDB_PORT=${FLIGHTSDB_PORT}
      - FLIGHTSDB_DATABASE=${FLIGHTSDB_DATABASE}
      - FLIGHTSDB_USER=${FLIGHTSDB_USER}
      - FLIGHTSDB_PASSWORD=${FLIGHTSDB_PASSWORD}
      - FLIGHTSDB_HOST=${FLIGHTSDB_HOST}
      - OPENSKY_SECRET_PATH=${OPENSKY_SECRET_PATH}
      - REDIST_HOST=${DATA_REDIS_HOST}
      - REDIST_PORT=${REDIS_PORT}
    secrets:
      - opensky_secrets
    healthcheck:
      # Prova a connettersi a localhost:50051. Se riesce, esce con 0 (OK).
      test: ["CMD-SHELL", "python3 -c \"import socket; s = socket.socket(socket.AF_INET, socket.SOCK_STREAM); s.connect(('localhost', 50051));\""]
      interval: 5s
      timeout: 5s
      retries: 5
      start_period: 40s
    depends_on:
      flights_db: 
        condition: service_healthy
      data-cache:
          condition: service_healthy
      broker-kafka-1: 
        condition: service_healthy
      broker-kafka-2: 
        condition: service_healthy
      broker-kafka-3: 
        condition: service_healthy
      kafka-init:
        condition: service_completed_successfully
    networks:
      - data-network
      - gateway-network
      - kafka-network
    restart: on-failure

  data-cache: 
    image: redis:alpine
    container_name: data-cache
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 3s
      timeout: 3s
      retries: 5
      start_period: 30s
    restart: always
    networks:
      - data-network

  user-db: 
    image: mariadb:10.11
    container_name: user-db
    restart: always 
    environment:
      - MARIADB_ROOT_PASSWORD=${PASSWORD_ROOT_DB}
      - MARIADB_DATABASE=${NAME_DB}
      - MARIADB_USER=${USER_DB}
      - MARIADB_PASSWORD=${PASSWORD_DB}
    healthcheck:
      test: ["CMD", "healthcheck.sh", "--connect", "--innodb_initialized"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 30s
    networks:
      - user-network
    volumes: 
      - userdb_data:/var/lib/mysql

  user-manager:
    build: ./user_manager
    container_name: user-manager
    restart: always
    environment:
      - PYTHONUNBUFFERED= 1
      - HOST_DB=${HOST_DB}
      - USER_DB=${USER_DB}
      - PASSWORD_DB=${PASSWORD_DB}
      - NAME_DB=${NAME_DB}
      - USER_DB_PORT=${USER_DB_PORT}
      - REDIST_HOST=${USER_REDIS_HOST}
      - REDIST_PORT=${REDIS_PORT}
      - JWT_PRIVATEKEY_SECRET_PATH=${JWT_PRIVATEKEY_SECRET_PATH}
    secrets:
      - jwt_privatekey_secret
    depends_on:
      user-db:
          condition: service_healthy
      user-cache:
          condition: service_healthy
    networks:
      - user-network
      - gateway-network
  
  user-cache: 
    image: redis:alpine
    container_name: user-cache
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 3s
      timeout: 3s
      retries: 5
      start_period: 30s
    restart: always
    networks:
      - user-network
      - gateway-network #black_list redis

volumes:
  flightdb_data:
  userdb_data:
  kafka_data_1:
  kafka_data_2:
  kafka_data_3:

networks:
  user-network:
  data-network:
  gateway-network:
  kafka-network:

secrets:
  opensky_secrets:
    file: "./data_collector/credentials.json"
  jwt_privatekey_secret:
    file: "./user_manager/private_key.pem"
