# When the load balancing method is not specifically configured, it defaults to round-robin
upstream user-manager-stream {
    server user-manager:5000;
}

upstream user-manager-grpc {
    server user-manager:50051;
}