
worker_processes 1;

events {
    # Symultaneous connections per worker
    worker_connections 1024;
}

http {

    # Shared dict to pass jwt public key to Lua scripts
    lua_shared_dict jwt_keys 1m;

    # Load the public key into shared memory at startup
    init_by_lua_block {
        local f = io.open("/etc/nginx/keys/public.pem", "rb")
        if f then
            local content = f:read("*all")
            f:close()
            ngx.shared.jwt_keys:set("public_key", content)
        else
            -- Se non trova la chiave, stampa un errore nei log di NGINX
            ngx.log(ngx.ERR, "Impossibile caricare /etc/nginx/keys/public.pem")
        end
    }

    server {
        listen 443 ssl;
        
        # Fix http2
        http2 on;

        
        # External file to map file extensions. (e.g., .html, .json, .jpg).
        include       mime.types;

        # Default MIME type if none found on mime.types.
        default_type  application/octet-stream;
        
        # Access log to store all requests
        access_log /usr/local/openresty/nginx/logs/access.log;
        
        # Error log to store errors and debug info
        error_log  /usr/local/openresty/nginx/logs/error.log;

        # Zero-copy optimization for file serving. Disk -> Network instead of Disk -> RAM -> Network.
        sendfile        on;

        # Keep TCP connections alive for 65 seconds. If a client makes multiple requests, can reuse the same connection.
        keepalive_timeout  65;

        # SSL Configuration
        ssl_certificate /etc/nginx/ssl/nginx.crt;
        ssl_certificate_key /etc/nginx/ssl/nginx.key;
        
        # Protocolli sicuri (Opzionale ma consigliato)
        ssl_protocols TLSv1.2 TLSv1.3;
        ssl_ciphers HIGH:!aNULL:!MD5;

        # resolver 127.0.0.11 valid=30s ipv6=off; DNS INTERNAL SERVER ON DOCKER
        resolver 10.96.0.10 valid=30s ipv6=off; # DNS INTERNAL SERVER ON KUBERNETES 

        # Health check and metrics endpoints (disabled)
        location ~ ^/.*(health|metrics)$ {
            access_log off;
            return 404;
        }

        # Public Routes
        location /auth/ {
            proxy_pass http://user-manager.default.svc.cluster.local:5000;
        }

        # Protected Routes (Data Collector and User Manager)
        location /flights/ {
            # JWT Token validation on Lua
            access_by_lua_file /etc/nginx/lua/jwt_validator.lua;

            proxy_pass http://data-collector.default.svc.cluster.local:5000/;
        }

        location /users/ {
            access_by_lua_file /etc/nginx/lua/jwt_validator.lua;
        
            proxy_pass http://user-manager.default.svc.cluster.local:5000;
        }
    }
    
    # Auto-redirect HTTP to HTTPS
    server {
        listen 80;
        return 308 https://$host$request_uri; # 308 (Permanent Redirect)
    }
}