apiVersion: v1
kind: ConfigMap
metadata:
  name: app-config
data:
  # Host interni del cluster (corrispondono ai nomi dei Service K8s)
  
  # Indirizzo del cluster Kafka (Headless Service per StatefulSet)
  KAFKA_BOOTSTRAP: "kafka-0.kafka-headless:9092,kafka-1.kafka-headless:9092,kafka-2.kafka-headless:9092"