# --- Alert System ---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: alert-system
spec:
  replicas: 1
  selector:
    matchLabels:
      app: alert-system
  template:
    metadata:
      labels:
        app: alert-system
    spec:
      containers:
      - name: alert-system
        image: local/alert-system:v1
        imagePullPolicy: Never
        envFrom:
        - secretRef:
            name: app-secrets
        - configMapRef:
            name: app-config