# --- Data Collector ---
apiVersion: v1
kind: Service
metadata:
  name: data-collector
spec:
  type: ClusterIP
  ports:
  - name: http
    port: 5000
    targetPort: 5000
  selector:
    app: data-collector
---
# there isn't a single Cluster IP for the gRPC service. With headless service, each pod gets its own DNS entry. 
# So when a client looks up the service name, it gets back multiple records (All pod's IP), one for each pod.
apiVersion: v1 
kind: Service
metadata:
  name: data-collector-headless 
spec:
  clusterIP: None 
  selector:
    app: data-collector
  ports:
  - name: grpc
    port: 50051
    targetPort: 50051
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: data-collector
spec:
  replicas: 3
  selector:
    matchLabels:
      app: data-collector
  template:
    metadata:
      labels:
        app: data-collector
      annotations: 
        # For Prometheus auto scraping
        prometheus.io/scrape: "true"
        prometheus.io/port: "8000"
    spec:
      containers:
      - name: data-collector
        image: local/data-collector:v1
        imagePullPolicy: Never
        resources:
          requests:
            memory: "512Mi"
            cpu: "500m"
          limits:
            memory: "1Gi"
            cpu: "1000m"
        envFrom:
        - secretRef:
            name: app-secrets
        - configMapRef:
            name: app-config
        volumeMounts:
        - name: secret-vol
          mountPath: "/secrets"
          readOnly: true
        livenessProbe: # Check if the app is running
          httpGet:
            path: /health
            port: 5000
          initialDelaySeconds: 15
          periodSeconds: 10
          timeoutSeconds: 5
          failureThreshold: 3
        readinessProbe: # Check if the app is ready to accept traffic 
          httpGet:
            path: /health
            port: 5000
          initialDelaySeconds: 10
          periodSeconds: 5
          timeoutSeconds: 3
          failureThreshold: 2
      topologySpreadConstraints: # Distribute pods evenly across nodes improving availability
        - maxSkew: 1 # Max 2 data-collector pods on a node
          topologyKey: kubernetes.io/hostname
          whenUnsatisfiable: ScheduleAnyway 
          labelSelector:
            matchLabels:
              app: data-collector
      volumes:
      - name: secret-vol
        secret:
          secretName: app-secrets
          items:
          - key: credentials.json
            path: credentials.json