apiVersion: batch/v1
kind: CronJob
metadata:
  name: flight-data-updater
spec:
  # 8hrs scheduling
  schedule: "0 * */8 * *"
  concurrencyPolicy: Forbid # Avoid overlapping runs, useful on test
  jobTemplate:
    spec:
      backoffLimit: 3 # Retry up to 3 times if fails
      template:
        spec:
          containers:
          - name: updater
            image: local/data-collector:v1
            imagePullPolicy: IfNotPresent
            command: ["python", "src/cron_runner.py"]          
            envFrom:
              - configMapRef:
                  name: app-config
              - secretRef:
                  name: app-secrets
            volumeMounts:
            - name: secret-vol
              mountPath: "/secrets"
              readOnly: true
          restartPolicy: OnFailure
          volumes:
          - name: secret-vol
            secret:
              secretName: app-secrets
              items:
              - key: credentials.json
                path: credentials.json
