# --- User Cache ---
apiVersion: v1
kind: Service
metadata:
  name: user-cache
spec:
  ports:
  - port: 6379
  selector:
    app: user-cache
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: user-cache
spec:
  replicas: 1
  selector:
    matchLabels:
      app: user-cache
  template:
    metadata:
      labels:
        app: user-cache
    spec:
      containers:
      - name: redis
        image: redis:alpine
        imagePullPolicy: IfNotPresent
        readinessProbe:
          exec:
            command: ["redis-cli", "ping"]
          initialDelaySeconds: 5
          periodSeconds: 3