# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

import user_service_pb2 as user__service__pb2

GRPC_GENERATED_VERSION = '1.76.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + ' but the generated code in user_service_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class DeleteUserInterestsServiceStub(object):
    """questo e' il file .proto in cui si definiscono le funzioni
    che permettono la comunicazione tra i due microservizi. 

    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.DeleteUserInterests = channel.unary_unary(
                '/DeleteUserInterestsService/DeleteUserInterests',
                request_serializer=user__service__pb2.DeleteUserInterestsRequest.SerializeToString,
                response_deserializer=user__service__pb2.DeleteUserInterestsResponse.FromString,
                _registered_method=True)


class DeleteUserInterestsServiceServicer(object):
    """questo e' il file .proto in cui si definiscono le funzioni
    che permettono la comunicazione tra i due microservizi. 

    """

    def DeleteUserInterests(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_DeleteUserInterestsServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'DeleteUserInterests': grpc.unary_unary_rpc_method_handler(
                    servicer.DeleteUserInterests,
                    request_deserializer=user__service__pb2.DeleteUserInterestsRequest.FromString,
                    response_serializer=user__service__pb2.DeleteUserInterestsResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'DeleteUserInterestsService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('DeleteUserInterestsService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class DeleteUserInterestsService(object):
    """questo e' il file .proto in cui si definiscono le funzioni
    che permettono la comunicazione tra i due microservizi. 

    """

    @staticmethod
    def DeleteUserInterests(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/DeleteUserInterestsService/DeleteUserInterests',
            user__service__pb2.DeleteUserInterestsRequest.SerializeToString,
            user__service__pb2.DeleteUserInterestsResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
